import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:flutter_client/crypto/double_ratchet.dart';
import 'package:flutter_client/crypto/key_backup.dart';
import 'package:flutter_client/crypto/keys.dart';
import 'package:flutter_client/crypto/message_crypto.dart';
import 'package:flutter_client/crypto/ratchet_facade.dart';
import 'package:flutter_client/crypto/ratchet_session_store.dart';
import 'package:flutter_client/crypto/sender_keys.dart';
import 'package:flutter_client/crypto/at_rest.dart';

/// Cross-language crypto vectors generated by test/gen_vectors.py (Python).
Map<String, dynamic> _vectors() {
  final candidates = [
    File('${Directory.current.path}/vectors.json'),
    File('${Directory.current.path}/test/vectors.json'),
  ];
  for (final f in candidates) {
    if (f.existsSync()) {
      return jsonDecode(f.readAsStringSync()) as Map<String, dynamic>;
    }
  }
  throw Exception('vectors.json not found (tried ${candidates.map((f) => f.path)})');
}

void main() {
  final v = _vectors();

  test('Ed25519 sign matches Python (deterministic seed)', () async {
    final seed = List<int>.generate(32, (i) => i);
    final sig = await edSign(utf8.encode('hello world'), seed);
    expect(base64Encode(sig), v['ed_sign']);
    expect(base64Encode(await ed25519PublicBytes(seed)), v['ed_pub']);
  });

  test('X25519 public + shared secret match Python', () async {
    final alice = List<int>.generate(32, (i) => i + 1);
    final bob = List<int>.generate(32, (i) => i + 33);
    final bobPub = await x25519PublicBytes(bob);
    final shared = await deriveInitialSharedSecret(alice, bobPub);
    expect(base64Encode(shared), v['initial_shared']);
  });

  test('v1 MessageEncryptor round-trips and matches Python vector shape',
      () async {
    final edPriv = List<int>.generate(32, (i) => i);
    final xPriv = List<int>.generate(32, (i) => i + 32);
    final xPub = await x25519PublicBytes(xPriv);
    final result = await MessageEncryptor.encryptMessage(
      plaintext: 'Привет, мир!',
      recipientX25519Pub: xPub,
      senderEd25519Priv: edPriv,
      senderEd25519Pub: await ed25519PublicBytes(edPriv),
      senderX25519Priv: xPriv,
      senderX25519Pub: xPub,
      senderId: '7',
      recipientId: '9',
    );
    // Python's blob is canonical (sorted keys) — decrypt must reproduce body.
    final decrypted = await MessageDecryptor.decryptMessage(
      {'blob': result['blob']!, 'signature': result['signature']!},
      xPriv,
      xPub,
      await ed25519PublicBytes(edPriv),
    );
    expect(decrypted, 'Привет, мир!');
    // Signature must verify against the canonicalized blob bytes.
    final blobBytes = base64Decode(result['blob']!);
    final parsed = jsonDecode(utf8.decode(blobBytes)) as Map<String, dynamic>;
    final reCanon = utf8.encode(serializeCanonical(parsed));
    expect(
        await edVerify(reCanon, base64Decode(result['signature']!),
            await ed25519PublicBytes(edPriv)),
        isTrue);
  });

  test('v2 ratchet blob canonical form + Python decryption-compatible AAD',
      () async {
    final xPriv = List<int>.generate(32, (i) => i + 32);
    final xPub = await x25519PublicBytes(xPriv);
    final edPriv = List<int>.generate(32, (i) => i);
    final bob = List<int>.generate(32, (i) => i + 33);
    final bobPub = await x25519PublicBytes(bob);

    final blob = await RatchetEncryptor.encryptMessage(
      plaintext: 'ratchet msg',
      peerKey: 'bob@example.org',
      peerIdentityX25519Pub: bobPub,
      senderEd25519Priv: edPriv,
      senderEd25519Pub: await ed25519PublicBytes(edPriv),
      senderX25519Priv: xPriv,
      senderX25519Pub: xPub,
      senderId: '7',
      recipientId: '9',
      store: MemoryRatchetSessionStore(),
    );

    final blobBytes = base64Decode(blob['blob']!);
    final parsed = jsonDecode(utf8.decode(blobBytes)) as Map<String, dynamic>;
    final reCanon = utf8.encode(serializeCanonical(parsed));
    expect(
        await edVerify(reCanon, base64Decode(blob['signature']!),
            await ed25519PublicBytes(edPriv)),
        isTrue);
    // AAD construction must be canonical: derive it the same way Python does.
    final ad = utf8.encode(canonicalJson({
      'v': 2,
      'dh': parsed['dh'],
      'pn': parsed['pn'],
      'n': parsed['n'],
    }));
    expect(ad, isNotEmpty);
  });

  test('group sender-key: wrap/unwrap + decrypt Python blob', () async {
    final bob = List<int>.generate(32, (i) => i + 33);
    final bobPub = await x25519PublicBytes(bob);

    final chain = SenderChainState(
      generation: 0,
      iteration: 0,
      chainKey: Uint8List.fromList(List<int>.generate(32, (i) => i + 200)),
    );

    // Reproduce Python's fixed-ephemeral distribution blob byte-for-byte.
    final fixedEph = base64Decode(v['group']['fixed_eph_priv'] as String);
    final ephPub = await x25519PublicBytes(fixedEph);
    final payload = utf8.encode(canonicalJson({
      'v': 1,
      't': 'sender-key',
      'gen': chain.generation,
      'ck': base64Encode(chain.chainKey),
    }));
    final shared = await xShared(fixedEph, bobPub);
    final wrapKey = await hkdf(
        shared, [...ephPub, ...bobPub], utf8.encode('tlc-sender-key-dist-v1'), 32);
    expect(base64Encode(wrapKey), v['group']['dist_wrap_key']);
    expect(base64Encode(payload), v['group']['dist_payload_bytes']);
    final nonce = List<int>.generate(12, (i) => i); // must not matter: fixed ct
    final ct = await aesEncrypt(payload, wrapKey, nonce: nonce);
    final blob = utf8.encode(canonicalJson({
      'v': 1,
      'ephemeral_pub': base64Encode(ephPub),
      'ct': base64Encode([...nonce, ...ct]),
    }));
    final myDist = base64Encode(blob);
    expect(myDist, v['group']['fixed_dist_blob']);

    // Dart unwraps Python's deterministic blob.
    final chain2 = await unwrapDistribution(myDist, bob);

    // Payload serialization: Dart emits raw UTF-8 while Python's json.dumps
    // escapes non-ASCII as \uXXXX (ensure_ascii). The payload is opaque (it is
    // AES-GCM encrypted), so byte equality is NOT required for interop — both
    // sides json-decode it identically. Compare parsed content instead.
    final groupPayload = utf8.encode(canonicalJson({
      't': 'group-payload',
      'v': 1,
      'body': 'группа!',
      'files': {'5': 'a2V5'},
    }));
    final parsedPayload = jsonDecode(utf8.decode(groupPayload)) as Map<String, dynamic>;
    final pyParsed = jsonDecode(utf8.decode(base64Decode(
        v['group']['payload_bytes'] as String))) as Map<String, dynamic>;
    expect(parsedPayload, pyParsed);

    final (blobDict, mk, newChain) =
        await encryptGroupMessage(chain2, groupPayload);
    // Deterministic outputs: message key and advanced chain.
    expect(base64Encode(mk), v['group']['message_key']);
    expect(base64Encode(newChain.chainKey), v['group']['new_chain_key']);
    expect(newChain.iteration, v['group']['new_chain_iteration']);

    // Cross-language: decrypt Python's serialized blob with our chain.
    final pyBlobB64 = v['group']['serialized_blob'] as String;
    final (plain, chainAfter) = await decryptGroupMessage(pyBlobB64, chain2);
    final decryptedPayload =
        jsonDecode(utf8.decode(plain)) as Map<String, dynamic>;
    expect(decryptedPayload, pyParsed);
    // Same deterministic chain advance as Python's own encrypt.
    expect(base64Encode(chainAfter.chainKey), v['group']['new_chain_key']);

    // Structural equality: same keys, same canonical key order.
    final serialized = utf8.encode(serializeBlob(blobDict));
    final mine = jsonDecode(utf8.decode(serialized)) as Map<String, dynamic>;
    final theirs =
        jsonDecode(utf8.decode(base64Decode(pyBlobB64))) as Map<String, dynamic>;
    expect(mine.keys.toList(), theirs.keys.toList());
    expect(mine['v'], theirs['v']);
    expect(mine['gen'], theirs['gen']);
    expect(mine['n'], theirs['n']);
  });

  test('key backup: byte-for-byte + cross-decrypt Python blob', () async {
    final edPriv = List<int>.generate(32, (i) => i);
    final xPriv = List<int>.generate(32, (i) => i + 32);

    // Reproduce Python's deterministic backup blob byte-for-byte (fixed
    // salt=0..15, nonce=16..27) — the format is salt||nonce||ct.
    final salt = List<int>.generate(16, (i) => i);
    final nonce = List<int>.generate(12, (i) => i + 16);
    // Python's json.dumps default separators use spaces: `, ` and `: `.
    final plaintext =
        utf8.encode('{"ed25519_priv": "${base64Encode(edPriv)}", '
            '"x25519_priv": "${base64Encode(xPriv)}", "version": 1}');
    final key = await pbkdf2(utf8.encode('password123'), salt, 600000, 256);
    final ct = await aesEncrypt(plaintext, key, nonce: nonce);
    final mine = <int>[...salt, ...nonce, ...ct];
    expect(base64Encode(mine), v['backup']);

    // Decrypt Python's blob.
    final (ed, x) =
        await KeyBackupManager.decryptBackup(base64Decode(v['backup'] as String), 'password123');
    expect(base64Encode(ed), base64Encode(edPriv));
    expect(base64Encode(x), base64Encode(xPriv));
  });

  test('at_rest seal/open round-trips', () async {
    final key = await deriveStorageKey(
        List<int>.generate(32, (i) => i + 32), 'alice', 'store');
    final sealed = await seal(key, {'a': 1, 'b': 'x'});
    final opened = await openValue(key, sealed);
    expect(opened, {'a': 1, 'b': 'x'});
  });

  test('v1 sender blob (buildSenderBlob) decrypts via decryptOwnMessage',
      () async {
    final xPriv = List<int>.generate(32, (i) => i + 32);
    final xPub = await x25519PublicBytes(xPriv);
    final messageKey = randomBytes(32);
    final plaintext = utf8.encode('own copy check');

    final blobBytes = await buildSenderBlob(
        messageKey, plaintext, xPriv, xPub, '7', '9');
    final senderBlobB64 = base64Encode(blobBytes);

    final restored = await MessageDecryptor.decryptOwnMessage(
        senderBlobB64, xPriv, xPub);
    expect(restored, 'own copy check');
  });
}