BORDER_RADIUS = 10

# Dark mode (getting into integration later)
# COL_BACKGROUND="#0F172A"
# COL_CARD="#1E293B"
# COL_BUTTON="#3182CE"
# COL_BUTTON_DISABLED="#475569"
# COL_TEXT_FIELD="#334155"
# COL_TEXT="#F8FAFC"
# COL_BUTTON_TEXT="#FFFFFF"

COL_BACKGROUND="#F0F4F8"
COL_CARD="#FFFFFF"
COL_BUTTON="#2B6CB0"
COL_BUTTON_DISABLED="#A0AEC0"
COL_TEXT_FIELD="#EDF2F7"
COL_TEXT="#1A365D"
COL_BUTTON_TEXT="#FFFFFF"

DAT_AUTH_EMAIL_DELAY = 0.2